// <auto-generated />
using System;
using CallTrackingSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CallTrackingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129043251_SetRowVersionDefaultSqlite")]
    partial class SetRowVersionDefaultSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CallRecordHandler", b =>
                {
                    b.Property<int>("CallRecordsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandlersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CallRecordsId", "HandlersId");

                    b.HasIndex("HandlersId");

                    b.ToTable("CallRecordHandlers", (string)null);
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.CallRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaqReference")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("InquirySystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasDefaultValueSql("randomblob(8)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InquirySystemId")
                        .HasDatabaseName("IX_CallRecords_InquirySystem");

                    b.HasIndex("LockedByUserId")
                        .HasDatabaseName("IX_CallRecords_Lock")
                        .HasFilter("[LockedByUserId] IS NOT NULL");

                    b.HasIndex("CreatedAt", "Status", "UrgencyLevel")
                        .IsDescending(true, false, false)
                        .HasDatabaseName("IX_CallRecords_Search");

                    b.ToTable("CallRecords", (string)null);
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.ChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CallRecordId", "ChangedAt")
                        .HasDatabaseName("IX_ChangeHistories_Record");

                    b.ToTable("ChangeHistories", (string)null);
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.Handler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineUserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Handlers_Active");

                    b.HasIndex("LineUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Handlers_LineUserId")
                        .HasFilter("[LineUserId] IS NOT NULL");

                    b.ToTable("Handlers", (string)null);
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.HandlerMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HandlerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InquirySystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InquirySystemId");

                    b.HasIndex("HandlerId", "InquirySystemId")
                        .IsUnique()
                        .HasDatabaseName("IX_HandlerMappings_Unique");

                    b.ToTable("HandlerMappings", (string)null);
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.InquirySystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_InquirySystems_Active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_InquirySystems_Name");

                    b.ToTable("InquirySystems", (string)null);
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CallRecordId")
                        .HasDatabaseName("IX_NotificationLogs_CallRecord");

                    b.HasIndex("Success", "SentAt")
                        .HasDatabaseName("IX_NotificationLogs_Failure")
                        .HasFilter("[Success] = 0");

                    b.ToTable("NotificationLogs", (string)null);
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineUserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LineUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_LineUserId")
                        .HasFilter("[LineUserId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CallRecordHandler", b =>
                {
                    b.HasOne("CallTrackingSystem.Core.Entities.CallRecord", null)
                        .WithMany()
                        .HasForeignKey("CallRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CallTrackingSystem.Core.Entities.Handler", null)
                        .WithMany()
                        .HasForeignKey("HandlersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.CallRecord", b =>
                {
                    b.HasOne("CallTrackingSystem.Core.Entities.InquirySystem", "InquirySystem")
                        .WithMany("CallRecords")
                        .HasForeignKey("InquirySystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InquirySystem");
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.ChangeHistory", b =>
                {
                    b.HasOne("CallTrackingSystem.Core.Entities.CallRecord", "CallRecord")
                        .WithMany("ChangeHistories")
                        .HasForeignKey("CallRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallRecord");
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.HandlerMapping", b =>
                {
                    b.HasOne("CallTrackingSystem.Core.Entities.Handler", "Handler")
                        .WithMany("HandlerMappings")
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CallTrackingSystem.Core.Entities.InquirySystem", "InquirySystem")
                        .WithMany("HandlerMappings")
                        .HasForeignKey("InquirySystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Handler");

                    b.Navigation("InquirySystem");
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.NotificationLog", b =>
                {
                    b.HasOne("CallTrackingSystem.Core.Entities.CallRecord", "CallRecord")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("CallRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallRecord");
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.CallRecord", b =>
                {
                    b.Navigation("ChangeHistories");

                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.Handler", b =>
                {
                    b.Navigation("HandlerMappings");
                });

            modelBuilder.Entity("CallTrackingSystem.Core.Entities.InquirySystem", b =>
                {
                    b.Navigation("CallRecords");

                    b.Navigation("HandlerMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
